;;; reader-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from reader.el

(defconst reader-supported-formats (list "pdf" "epub" "mobi" "fb2" "xps" "cbz" "docx" "pptx" "xlsx" "odt" "ods" "odp" "odg") "\
File formats supported by the document reader.")
(autoload 'reader-open-doc "reader" "\
Open DOCUMENT for viewing.

This function calls the module function `reader-dyn--load-doc' from the
dynamic module to render the first page and displays it in a new buffer.

The only formats that can be opened `reader-supported-formats', any
other file format will simply not show up as a candidate.

(fn DOCUMENT)" t)
(autoload 'reader-mode "reader" "\
Major mode for viewing documents in The Emacs Reader.

Keybindings:
\\{reader-mode-map}

(fn)" t)
(dolist (pattern reader-supported-formats) (add-to-list 'auto-mode-alist (cons (concat "\\." pattern "\\'") 'reader-mode)))
(register-definition-prefixes "reader" '("reader-"))


;;; Generated autoloads from reader-bookmark.el

(autoload 'reader-bookmark-jump "reader-bookmark" "\
Handles BOOKMARK for record type returned by `reader-bookmark-make-record'.

(fn BOOKMARK)")
(register-definition-prefixes "reader-bookmark" '("reader-bookmark-make-record"))


;;; Generated autoloads from reader-outline.el

(autoload 'reader--outline-make-imenu-entry "reader-outline" "\
Convert one outline PLIST to an imenu entry.

(fn PLIST)")
(autoload 'reader--outline-imenu-create-index "reader-outline" "\
Turn `reader-current-doc-outline' into an imenu index.")
(autoload 'reader--outline-imenu-goto "reader-outline" "\
Switch to PAGE.

Ignores the _NAME argument.
Just wraps `reader-goto-page' for imenu compatibility.

(fn NAME PAGE)")
(autoload 'reader-outline-show "reader-outline" "\
Show the document outline in a separate buffer.

The outline buffer inherits it's name from the original
document it was created from." t)
(register-definition-prefixes "reader-outline" '("reader-"))


;;; Generated autoloads from reader-saveplace.el

(autoload 'reader--saveplace-find-file "reader-saveplace" "\
Restore saved place in `reader-mode' buffers.

To be added to `save-place-after-find-file-hook'.  See also `reader--saveplace-to-alist'.")
(add-hook 'save-place-after-find-file-hook #'reader--saveplace-find-file)
(autoload 'reader--saveplace-to-alist "reader-saveplace" "\
Save place in `reader-mode' buffers or call ORIG-FUN with ARGS.

Advice around `save-place-to-alist'.  See also `reader--saveplace-find-file'.

(fn ORIG-FUN &rest ARGS)")
(advice-add 'save-place-to-alist :around #'reader--saveplace-to-alist)

;;; End of scraped data

(provide 'reader-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; reader-autoloads.el ends here
